### ISSUE TITLE
node-gyp rebuild fails

### ISSUE THREAD

**Issue by nbrustein** [desmondmorris/node-tesseract#30]
node v5.4.1
npm v3.5.3

	gyp ERR! build error
	gyp ERR! stack Error: `make` failed with exit code: 2
	gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
	gyp ERR! stack     at emitTwo (events.js:87:13)
	gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
	gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
	gyp ERR! System Darwin 14.5.0
	gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
	gyp ERR! cwd /Users/nbrustein/code/bantley/node_modules/tesseract
	gyp ERR! node -v v5.4.1
	gyp ERR! node-gyp -v v3.2.1
	gyp ERR! not ok
	npm ERR! Darwin 14.5.0
	npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "tesseract"
	npm ERR! node v5.4.1
	npm ERR! npm  v3.5.3
	npm ERR! code ELIFECYCLE

	npm ERR! tesseract@0.0.3 install: `node-gyp rebuild`
	npm ERR! Exit status 1
	npm ERR!
	npm ERR! Failed at the tesseract@0.0.3 install script 'node-gyp rebuild'.
	npm ERR! Make sure you have the latest version of node.js and npm installed.
	npm ERR! If you do, this is most likely a problem with the tesseract package,
	npm ERR! not with npm itself.
	npm ERR! Tell the author that this fails on your system:
	npm ERR!     node-gyp rebuild
	npm ERR! You can get information on how to open an issue for this project with:
	npm ERR!     npm bugs tesseract
	npm ERR! Or if that isn't available, you can get their info via:
	npm ERR!     npm owner ls tesseract
	npm ERR! There is likely additional logging output above.

**Comment by nbrustein** [comment]
This seemed to fix it:

https://github.com/mdelete/node-tesseract-native/issues/8
