### ISSUE TITLE
help...I can't get the module working

### ISSUE THREAD

**Issue by SPlatten** [desmondmorris/node-tesseract#44]
[Edit] 06/04/2017 @ 19:26:00 GMT, well I've got it running, but sadly out of a 4 page PDF, the OCR failed completely it didn't manage to correctly identify anything in the document and the PDF is very clear it isn't a scan.  What was presently the installation from working was the missing english file from tessdata.

[Original post below]

I have an iMac running macOS Sierra version 10.12.4, node v7.10.0

I've installed tesseract and the module, I've defined the environment variable:

         export TESSDATA_PREFIX="/docfire/tesseract/tessdata/"

However when I try to execute the js I get:

{ Error: Command failed: tesseract /docfire/EON-0.png /var/folders/q7/hnxl054d71q277m5c3j25vdh0000gn/T/node-tesseract-ca36ca41-90a4-4c9b-af03-e7b4fcb13256 -l eng -psm 3
Error opening data file /docfire/tesseract/eng.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.
Failed loading language 'eng'
Tesseract couldn't load any languages!
Could not initialize tesseract.

    at ChildProcess.exithandler (child_process.js:205:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:511:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'tesseract /docfire/EON-0.png /var/folders/q7/hnxl054d71q277m5c3j25vdh0000gn/T/node-tesseract-ca36ca41-90a4-4c9b-af03-e7b4fcb13256 -l eng -psm 3' }
{ Error: Command failed: tesseract /docfire/EON-1.png /var/folders/q7/hnxl054d71q277m5c3j25vdh0000gn/T/node-tesseract-b6b7a7c9-5bf6-45dd-ba2c-bc310ee7bf0a -l eng -psm 3
Error opening data file /docfire/tesseract/eng.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.
Failed loading language 'eng'
Tesseract couldn't load any languages!
Could not initialize tesseract.

    at ChildProcess.exithandler (child_process.js:205:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:511:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'tesseract /docfire/EON-1.png /var/folders/q7/hnxl054d71q277m5c3j25vdh0000gn/T/node-tesseract-b6b7a7c9-5bf6-45dd-ba2c-bc310ee7bf0a -l eng -psm 3' }
{ Error: Command failed: tesseract /docfire/EON-2.png /var/folders/q7/hnxl054d71q277m5c3j25vdh0000gn/T/node-tesseract-8a076c14-2a91-412f-b290-e1990cf2626c -l eng -psm 3
Error opening data file /docfire/tesseract/eng.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.
Failed loading language 'eng'
Tesseract couldn't load any languages!
Could not initialize tesseract.

    at ChildProcess.exithandler (child_process.js:205:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:511:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'tesseract /docfire/EON-2.png /var/folders/q7/hnxl054d71q277m5c3j25vdh0000gn/T/node-tesseract-8a076c14-2a91-412f-b290-e1990cf2626c -l eng -psm 3' }
{ Error: Command failed: tesseract /docfire/EON-3.png /var/folders/q7/hnxl054d71q277m5c3j25vdh0000gn/T/node-tesseract-0b90e63f-076e-4956-aa47-b868cfecb42d -l eng -psm 3
Error opening data file /docfire/tesseract/eng.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.
Failed loading language 'eng'
Tesseract couldn't load any languages!
Could not initialize tesseract.

    at ChildProcess.exithandler (child_process.js:205:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:511:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'tesseract /docfire/EON-3.png /var/folders/q7/hnxl054d71q277m5c3j25vdh0000gn/T/node-tesseract-0b90e63f-076e-4956-aa47-b868cfecb42d -l eng -psm 3' }

**Comment by SPlatten** [comment]
I've made a little progress by changing the document type from png to tiff, but there is still no output, if I run tesseract from the command line I do get some output, a single line is extract from a 4 page TIFF.
