### ISSUE TITLE
update npm package to fix ‘[DEP0013] DeprecationWarning ...’

### ISSUE THREAD

**Issue by wangzexi** [desmondmorris/node-tesseract#50]
```
(node:38459) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is de
precated.
```

This commit fix this problem, but package from npm still warning.

9d14f986d70c8a5ab1c0fa19e21f4571fe0ad961

**Comment by arjitkhullar** [comment]
This stack trace might help:

(node:12476) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
    at makeCallback (fs.js:127:12)
    at Object.fs.unlink (fs.js:1054:14)
    at C:\Apache24\htdocs\ocrify\node_modules\node-tesseract\lib\tesseract.js:99:14
    at tryToString (fs.js:512:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:500:12)

**Comment by alphatr** [comment]
Hi @desmondmorris , please update npm package.

**Comment by yangkean** [comment]
please update npm package to [`b01948228b`](https://github.com/desmondmorris/node-tesseract/tree/b01948228be2bd93a220011ddbf1a31e2078c390).

**Comment by jony89** [comment]
@desmondmorris ?

**Comment by Airat1995** [comment]
Problem still happen, when npm package will be updated?

**Comment by jeneser** [comment]
Please update npm package. +1

**Comment by BenjaminChoou** [comment]
Here is a contemporary solution:

### 1. Find where your node-tesseract module is.
On my computer, the path is :
```
C:\Users\BenjaminChou\node_modules\node-tesseract\lib
```
### 2.  Open and modify ```tesseract.js``` as follow:
Before:
```  fs.unlink(files[0]);```
Now:
``` fs.unlink(files[0], err => { if (err) console.log(err) });```

### Try it again. Good luck!

**Comment by kurorido** [comment]
`yarn add -D https://github.com/desmondmorris/node-tesseract/archive/30249786e35a2698dfae20c6534935d4f8d18420.tar.gz`
